sudo: false
language: python
cache: pip
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TOX_ENV=py27-dj19
  - python: 3.4
    env: TOX_ENV=py34-dj19
  - python: 3.5
    env: TOX_ENV=py35-dj19
  - python: 2.7
    env: TOX_ENV=py27-dj110
  - python: 3.4
    env: TOX_ENV=py34-dj110
  - python: 3.5
    env: TOX_ENV=py35-dj110
  - python: 2.7
    env: TOX_ENV=py27-dj111
  - python: pypy
    env: TOX_ENV=pypy-dj111
  - python: 3.4
    env: TOX_ENV=py34-dj111
  - python: 3.5
    env: TOX_ENV=py35-dj111
  - python: 3.6
    env: TOX_ENV=py36-dj111
  - python: pypy3
    env: TOX_ENV=pypy3-dj111
  - python: 3.4
    env: TOX_ENV=py34-dj20
  - python: 3.5
    env: TOX_ENV=py35-dj20
  - python: 3.6
    env: TOX_ENV=py36-dj20
  - python: 3.5
    env: TOX_ENV=py35-djdev
  - python: 3.6
    env: TOX_ENV=py36-djdev
  - python: 3.6
    env: TOX_ENV=flake8
  - python: 3.6
    env: TOX_ENV=isort
  - python: 3.6
    env: TOX_ENV=readme
  - python: 3.6
    env: TOX_ENV=check-manifest
  allow_failures:
  - env: TOX_ENV=py35-djdev
  - env: TOX_ENV=py36-djdev
install:
- pip install tox
script:
- tox -e "$TOX_ENV"
deploy:
  provider: pypi
  user: uncovertruth
  password:
    secure: FtNY+8/F79RYpJzfusYBC9HFfDWlevUbS4J5TECm8tyMxAxeHMpLOaL4dd/wPkRkuctUM5LyXux5rpVQTfMA4Dvjdufc7BqexCt056GznJPFRjHW19ExeguTHXW810RIVrFmo5Dk1/AlMpGEeiL3OXoI041h7/vRZe6QWP6P0NCz9UrkZ/Qc9JDZqkXBmhiwvt4P3gu5sbxaiM4IqxhSQ/4DoI87SQlD3nUfgRT2TkqN/Jx0ME0H7l+40HeqZvVq6sh9Muc5/XhDEx5HWt9BSgymeXXG6mT3sewBfinJlQ5/1Rrm+IHa48m/3mLJkfYEs15BQCizvDc6/dRfdtCc/9jYl3e67yEM6Akn+52pTOU4Oa727ZUpAYNCzfY+pHc3E9oI0YFuOl+WYNo5bWUh3IlWAl/eXDGWOvRMF4waUbyjUMiZ+C4pRmRKznYZB9xgbPxHDlR6CMn8P5F5j3ZVbW0BxUEjlDFcDT65gflBhKS1eWTOQRMobR+yjQKlYMlIeCgITbuEYbn2GbL84aN42U910rSQ4SryzqjaOIyxtZG53cGDw2NMm4q7bIwRkj6gbvliA36HIFaRQrI/wtrmr3guy4raPRpEGi7OhFoaPxaqkEs+yF55MEafNM4eJc9swM/K/mbN6FFKIWoWVyXUCUDIWvcPYLWPR/kLidWCNzw=
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    repo: uncovertruth/django-elastipymemcache
    tags: true
    condition: $TOX_ENV = py36-dj20
